### ISSUE TITLE
Give credit Immediately 

### ISSUE THREAD

**Issue by Guru322** [AbhishekSuresh2/ABHISHEK-SER#80]
If You are copy pasting my files , Give me proper credits 

Or I will take Legal action Against you

+91 81579 93101

**Comment by Iyin124** [comment]
Hey,Give credit or we'll take  legal action against you,very rude and stupid thing... Very Bad

**Comment by Iyin124** [comment]
Give credits man or face the wrath

**Comment by kingsksinha** [comment]
enough nigga give him credits

**Comment by Guru322** [comment]
+91 90746 92450

**Comment by AbhishekSuresh2** [comment]
Giving u just wait
